#!/bin/sh

# jailskype:
#   Start skypeforlinux in a customized firejail
#   (originally based on https://spwhitton.name/blog/entry/firejailskype/)
#
# Copyright © 2017 Rowan Thorpe <rowan@rowanthorpe.com>
#
# Any additional contributions are noted in the AUTHORS.md file.

# This file is part of jailskype.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

## config

js_version='0.1.0'
js_verbose='0'
js_debug='0'
js_sleep='0.2'
js_logfile=''
js_fakehome=''
js_home="${HOME}"; test -n "${js_home}" || js_home=~; js_home="${js_home%%/}"

## functions

doit() {
    ! test 1 = "${js_debug}" || printf '\n ==> %s\n\n' "${1}"
    if test 1 = "${js_verbose}"; then
        eval "${1}"
    else
        eval "${1}" >/dev/null 2>&1
    fi
}

## getopts

while test ${#} -ne 0; do
    case "${1}" in
        -h|--help|--usage)
            cat <<EOF
Usage: jailskype [OPTION]...
Start skypeforlinux in a customized firejail

  -v, --verbose     Show program output
  -d, --debug       Display each command before executing
  -s, --sleep-time  Time to sleep after skype closes before closing openbox
  -l, --log-file X  Filename to log to instead of stdout
  -H, --fake-home X Directory to use as fake \$HOME
                    (def: ${js_home}/jailskype-homedir)
  -h, --help        This message
  -V, --version     Show version of this wrapper

Home page: https://github.com/rowanthorpe/jailskype
EOF
            exit 0
            ;;
        -V|--version)
            cat <<EOF
jailskype ${js_version}
Copyright (C) 2017 Rowan Thorpe

License GPLv3+: GNU GPL 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
EOF
            exit 0
            ;;
        -v|--verbose)    js_verbose=1; shift ;;
        -v*)             js_verbose=1; arg1="-${1#-v}"; shift; set -- "${arg1}" "${@}" ;;
        -d|--debug)      js_debug=1; shift ;;
        -d*)             js_debug=1; arg1="-${1#-d}"; shift; set -- "${arg1}" "${@}" ;;
        -s|--sleep-time) js_sleep="${2}"; shift 2 ;;
        -l|--log-file)   js_logfile="${2}"; shift 2 ;;
        -H|--fake-home)  js_fakehome="${2}"; shift 2 ;;
        --)              shift; break ;;
        -*)              printf 'Unknown optflag "%s"\n' "${1}" >&2; exit 1 ;;
        *)               break ;;
    esac
done

## setup

js_fakehome="${js_fakehome:-${js_home}/jailskype-homedir}"
js_prefix="firejail --private=\"${js_fakehome}\" --private-tmp"
test -n "${js_logfile}" || js_logfile='/dev/stdout'
exec </dev/null >"${js_logfile}" 2>&1

# main

mkdir -p "${js_fakehome}"
doit "${js_prefix} --net=none --x11=xephyr openbox &"
while /bin/sleep 0.2; do ## Loop until new ${DISPLAY} found
    js_display="$(firemon --x11 | sed -n -e 's/^ \+DISPLAY \+//' -e 't P' -e 'b' -e ':P' -e 'p' -e 'q')"
    test -z "${js_display}" || break
done
js_prefix="DISPLAY=\"${js_display}\" ${js_prefix}"
doit "${js_prefix} --blacklist=/run/user/\$(id -u)/dconf/user --net=eth0 skypeforlinux"
/bin/sleep "${js_sleep}" # Hope this is enough time for skype to finish cleaning up
doit "${js_prefix} --net=none openbox --exit"
